"""Timeline of the chaotic group-chat video (v10-chat.html): who says what, and when each line lands.

    python3 v10_timeline.py    # writes v10-chat.timeline.js

Each line appears on its own like a real Discord chat; when the author changes, "X is typing…" shows
first. The avatars are the original characters from v9 (vo/v9/ziko.png, loli.png, hamo.png).
"""
import json
from pathlib import Path

here = Path(__file__).parent
USERS = {
    'ziko': {'name': 'زيكو', 'color': '#2f8f5b', 'tag': '💸 CC', 'img': 'vo/v9/ziko.png'},
    'loli': {'name': 'لولي', 'color': '#0e8fa6', 'tag': '🎮 lol', 'img': 'vo/v9/loli.png'},
    'hamo': {'name': 'حمو', 'color': '#b86a12', 'tag': '🤝 inv', 'img': 'vo/v9/hamo.png'},
}
# (author, time shown, lines, seconds between lines)
GROUPS = [
    ('ziko', '8:24 م', ['بقولكو', 'نعمل فيديو للسيرفر', 'وننزله على التيك', '#ديسكورد', '#كيوس', '#مود_السهر'], 0.55),
    ('loli', '8:24 م', ['ههههههههههههههههه اخخخ'], 0.6),
    ('hamo', '8:24 م', ['.', '.', '.', '.'], 0.3),
    ('ziko', '8:29 م', ['هيتشهر في يومين', 'فجأة', 'السيرفر يبقى فيه مليون واحد', 'وإحنا نبقى مشاهير'], 0.65),
    ('hamo', '8:29 م', ['وزيكو يخسر كل فلوسه في البورصة'], 0.6),
    ('ziko', '8:29 م', ['؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟'], 0.6),
    ('loli', '8:29 م', ['وأنا أبقى أدمن وأطرده 😭😂💀'], 0.6),
]


def main():
    t, prev, items = 0.4, None, []
    for who, time, lines, step in GROUPS:
        if who != prev:
            items.append({'kind': 'typing', 'who': who, 'at': round(t, 2), 'len': 0.7})
            t += 0.8
        items.append({'kind': 'head', 'who': who, 'time': time, 'at': round(t, 2)})
        for line in lines:
            items.append({'kind': 'line', 'who': who, 'text': line, 'at': round(t, 2)})
            t += step
        t += 0.35
        prev = who
    t += 0.5
    items.append({'kind': 'join', 'at': round(t, 2)})
    end = round(t + 3.6, 2)
    (here / 'v10-chat.timeline.js').write_text(
        '// Generated by v10_timeline.py. Do not edit by hand.\n'
        'window.TL = ' + json.dumps({'users': USERS, 'items': items, 'end': end}, ensure_ascii=False, indent=1) + ';\n',
        encoding='utf-8')
    print(f"{sum(1 for i in items if i['kind'] == 'line')} lines, join at {t:.2f}s, end {end}s")


if __name__ == '__main__':
    main()
