"""Timeline of the chaotic group-chat video (v10-chat.html): who says what, and when each line lands.

    python3 v10_timeline.py    # writes v10-chat.timeline.js

Each line appears on its own like a real Discord chat; when the author changes, "X is typing…" shows
first. The cast is the CHAOS admins; avatars live in vo/v10/av/ (gitignored),
and an admin with img None gets a Discord-style letter avatar on the bg color.
"""
import json
from pathlib import Path

here = Path(__file__).parent
USERS = {
    'oskar': {'name': 'oskar', 'color': '#c2185b', 'tag': '👑 OWNER', 'img': 'vo/v10/av/oskar.png'},
    'adam': {'name': 'adam', 'color': '#1e7fd1', 'tag': '🛡️ ADMIN', 'img': None, 'bg': '#5865f2'},
    '7assep': {'name': '7assep', 'color': '#7b3fc4', 'tag': '🛡️ ADMIN', 'img': 'vo/v10/av/7assep.png'},
    'zatona': {'name': 'zatona', 'color': '#2f8f5b', 'tag': '🛡️ ADMIN', 'img': None, 'bg': '#3ba55c'},
    'ali': {'name': 'ali', 'color': '#b86a12', 'tag': '🛡️ ADMIN', 'img': None, 'bg': '#faa61a'},
    'retlex': {'name': 'retlex', 'color': '#d83c3e', 'tag': '🛡️ ADMIN', 'img': 'vo/v10/av/retlex.png'},
}
# (author, time shown, lines, seconds between lines)
GROUPS = [
    ('oskar', '8:24 م', ['بقولكو', 'نعمل فيديو للسيرفر', 'وننزله على التيك', '#ديسكورد', '#كيوس', '#مود_السهر'], 0.5),
    ('adam', '8:24 م', ['ههههههههههههههههه اخخخ'], 0.55),
    ('7assep', '8:24 م', ['.', '.', '.', '.'], 0.3),
    ('oskar', '8:29 م', ['هيتشهر في يومين', 'فجأة', 'السيرفر يبقى فيه مليون واحد', 'وإحنا نبقى مشاهير'], 0.6),
    ('zatona', '8:29 م', ['وعلي يخسر كل فلوسه في البورصة'], 0.6),
    ('ali', '8:29 م', ['؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟'], 0.6),
    ('retlex', '8:29 م', ['وأنا أبقى الديكتاتور وأطرده 😭😂💀'], 0.6),
]


def main():
    t, prev, items = 0.4, None, []
    for who, time, lines, step in GROUPS:
        if who != prev:
            items.append({'kind': 'typing', 'who': who, 'at': round(t, 2), 'len': 0.6})
            t += 0.7
        items.append({'kind': 'head', 'who': who, 'time': time, 'at': round(t, 2)})
        for line in lines:
            items.append({'kind': 'line', 'who': who, 'text': line, 'at': round(t, 2)})
            t += step
        t += 0.35
        prev = who
    t += 0.5
    items.append({'kind': 'join', 'at': round(t, 2)})
    end = round(t + 3.6, 2)
    (here / 'v10-chat.timeline.js').write_text(
        '// Generated by v10_timeline.py. Do not edit by hand.\n'
        'window.TL = ' + json.dumps({'users': USERS, 'items': items, 'end': end}, ensure_ascii=False, indent=1) + ';\n',
        encoding='utf-8')
    print(f"{sum(1 for i in items if i['kind'] == 'line')} lines, join at {t:.2f}s, end {end}s")


if __name__ == '__main__':
    main()
