"""Timeline of the chat-story video (v4-story.html) from the ElevenLabs voice lines.

    python3 v4_timeline.py    # writes v4-story.timeline.js and vo/v4/plan.json

The voice files (vo/v4/01.mp3 … 12.mp3, pop.mp3, chaching.mp3, bed.mp3) come from the ElevenLabs
flow "CHAOS promo — chat story (v4)". Each line's length (silence trimmed, sped up by TEMPO) decides
when its chat bubble appears, so the picture always follows the voices.
"""
import json
import re
import subprocess
import wave
from pathlib import Path

import imageio_ffmpeg

here = Path(__file__).parent
vo = here / 'vo' / 'v4'
FF = imageio_ffmpeg.get_ffmpeg_exe()
TEMPO = 1.1
GAP = 0.25
TRIM = ('silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.02,areverse,'
        'silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.05,areverse')

A = {'name': 'زيزو', 'color': '#22d3ee', 'avatar': '😴'}
B = {'name': 'كيمو', 'color': '#ff5a6e', 'avatar': '😎'}
LINES = [  # (speaker, text shown in the chat); the spoken text is in the ElevenLabs flow
    ('A', 'يا عم أنا زهقت… السيرفر بتاعنا مات خالص 💀'),
    ('B', 'طب ما تيجي CHAOS؟'),
    ('A', 'CHAOS؟ ده إيه ده؟ 🤔'),
    ('B', 'سيرفر فيه ألعاب كل يوم 🎮 واللي يكسب بياخد CC'),
    ('A', 'CC إيه؟'),
    ('B', 'عملة السيرفر يا معلم 💰 وفيه بورصة كمان 📈'),
    ('B', 'أنا لسه شاري عربية بـ 1,180 وبعتها بـ 1,470 😂'),
    ('A', 'بجد؟! إزاي يعني؟ 😳'),
    ('B', 'الأسعار بتتغير كل ساعة… اشتري رخيص وبيع غالي'),
    ('B', 'ولو جبت صحابك ووصلوا لفل 5 تاخد 1000 CC على كل واحد 🔥'),
    ('A', 'طب ابعت اللينك بسرعة 🏃'),
]


def length(mp3):
    out = vo / 'tmp.wav'
    subprocess.run([FF, '-y', '-loglevel', 'error', '-i', mp3, '-af', f'{TRIM},atempo={TEMPO}', '-ac', '1', out], check=True)
    with wave.open(str(out)) as w:
        return w.getnframes() / w.getframerate()


def main():
    t = 1.2  # the hook caption is alone on screen first
    items, voices, pops, prev = [], [], [], None
    for i, (who, text) in enumerate(LINES, 1):
        d = length(vo / f'{i:02d}.mp3')
        if who == 'B' and prev != 'B':
            items.append({'kind': 'typing', 'at': round(t, 2), 'len': 0.45})
            t += 0.45
        items.append({'kind': 'msg', 'at': round(t - 0.1, 2), 'who': who, 'text': text,
                      'grouped': who == prev, 'speak': [round(t, 2), round(t + d, 2)]})
        pops.append(round(t - 0.1, 2))
        voices.append({'file': f'vo/v4/{i:02d}.mp3', 'at': round(t, 2), 'tempo': TEMPO})
        t += d
        if i == 7:
            t += 0.15
            items.append({'kind': 'card', 'id': 'trade', 'at': round(t, 2)})
            t += 1.0
        if i == 10:
            t += 0.15
            items.append({'kind': 'card', 'id': 'invite', 'at': round(t, 2)})
            t += 0.9
        t += GAP
        prev = who
    items.append({'kind': 'typing', 'at': round(t, 2), 'len': 0.35})
    t += 0.35
    items.append({'kind': 'card', 'id': 'link', 'at': round(t, 2)})
    t += 1.4
    cta = round(t, 2)
    d12 = length(vo / '12.mp3')
    voices.append({'file': 'vo/v4/12.mp3', 'at': round(cta + 0.45, 2), 'tempo': TEMPO})
    end = round(cta + 0.45 + d12 + 1.1, 1)
    cards = [x['at'] for x in items if x['kind'] == 'card']
    tl = {'A': A, 'B': B, 'items': items, 'cta': cta, 'end': end}
    (here / 'v4-story.timeline.js').write_text(
        '// Generated by v4_timeline.py from the ElevenLabs voice lengths. Do not edit by hand.\n'
        'window.TL = ' + json.dumps(tl, ensure_ascii=False, indent=1) + ';\n', encoding='utf-8')
    plan = {
        'video': 'out/v4-story.video.mp4', 'html': 'v4-story.html',
        'music': 'vo/v4/bed.mp3', 'music_offset': 0, 'music_until': cta,
        'music2': 'vo/v1/music.mp3', 'music2_offset': 3.5, 'music2_at': cta,
        'lines': voices,
        'sfx': [{'file': 'vo/v4/pop.mp3', 'at': p, 'gain': 0.5} for p in pops + cards[1:]]
               + [{'file': 'vo/v4/chaching.mp3', 'at': cards[0], 'gain': 0.8}],
        'out': 'out/v4-story-vo.mp4',
    }
    (vo / 'plan.json').write_text(json.dumps(plan, ensure_ascii=False, indent=1))
    html = here / 'v4-story.html'
    h = html.read_text(encoding='utf-8')
    h = re.sub(r'data-duration="[\d.]+"', f'data-duration="{end}"', h)
    h = re.sub(r'data-hits="[\d.,]+"', f'data-hits="{cta}"', h)
    h = re.sub(r'(class="scene chat" data-start="0" data-end=")[\d.]+', rf'\g<1>{round(cta + 0.25, 2)}', h)
    h = re.sub(r'(<section class="scene" data-start=")[\d.]+(" data-end=")[\d.]+', rf'\g<1>{cta}\g<2>{end}', h)
    html.write_text(h, encoding='utf-8')
    (vo / 'tmp.wav').unlink()
    print(f'{len(LINES)} messages, CTA at {cta}s, end {end}s')


if __name__ == '__main__':
    main()
