"""Timeline of the movie-trailer video (v5-trailer.html) from the ElevenLabs narrator lines.

    python3 v5_timeline.py    # writes v5-trailer.timeline.js and vo/v5/plan.json

Every scene lasts as long as its narrator line (silence trimmed) plus a lead-in and a tail, so the
picture follows the voice. Files in vo/v5/ come from the ElevenLabs flow "CHAOS promo — movie trailer (v5)":
01.mp3 … 11.mp3 (narrator: Gamal), 12.mp3 (Nadia, the message to girls), voice.png and bourse.png
(real screenshots from the server, upscaled 3x), braam.mp3, hit.mp3, riser.mp3, musicA.mp3 (dark intro),
musicB.mp3 (epic, from the logo on).
"""
import json
import re
import subprocess
import wave
from pathlib import Path

import imageio_ffmpeg

here = Path(__file__).parent
vo = here / 'vo' / 'v5'
FF = imageio_ffmpeg.get_ffmpeg_exe()
TRIM = ('silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.02,areverse,'
        'silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.05,areverse')

# The short cut: the real voice-channel screenshot is the hook, then logo, montage, the message to
# girls and the call to action. (scene, narrator line or None, lead-in, tail or fixed length)
# Narrator: Mostafa (young, energetic) in young Egyptian slang — y_*.mp3. The older, slower take by
# Gamal is still in vo/v5/01.mp3 … 11.mp3.
SEQ = [
    ('proof', 'y_hook', 0.15, 0.8),    # hook: opening night, Among Us, the voice channel is full
    ('logo', None, 0, 2.1),
    ('games', 'y_games', 0.1, 0.25),
    ('bourse', 'y_bourse', 0.1, 1.5),  # the real bourse board needs a moment to be read
    ('mafia', 'y_mafia', 0.1, 0.35),
    ('girls', 12, 0.3, 0.7),           # Nadia: girl-to-girl verification
    ('finale', 'y_finale', 0.35, 1.8),
]
# Speed per line.
TEMPO = {12: 1.05}
DEFAULT_TEMPO = 1.0


def length(mp3, tempo):
    out = vo / 'tmp.wav'
    subprocess.run([FF, '-y', '-loglevel', 'error', '-i', mp3, '-af', f'{TRIM},atempo={tempo}', '-ac', '1', out], check=True)
    with wave.open(str(out)) as w:
        return w.getnframes() / w.getframerate()


def main():
    t, scenes, lines = 0.0, {}, []
    for name, line, lead, tail in SEQ:
        start = t
        if line is None:
            t += tail
        else:
            tempo = TEMPO.get(line, DEFAULT_TEMPO)
            clip = line if isinstance(line, str) else f'{line:02d}'
            d = length(vo / f'{clip}.mp3', tempo)
            lines.append({'file': f'vo/v5/{clip}.mp3', 'at': round(start + lead, 2), 'tempo': tempo})
            t = start + lead + d + tail
        scenes[name] = [round(start, 2), round(t, 2)]
    end = round(t, 2)
    s = scenes
    sfx = [{'file': 'vo/v5/hit.mp3', 'at': 0.02, 'gain': 0.9},          # the hook lands with a hit
           {'file': 'vo/v5/braam.mp3', 'at': s['logo'][0], 'gain': 1.0}]
    sfx += [{'file': 'vo/v5/hit.mp3', 'at': s[n][0], 'gain': 0.85} for n in ('games', 'bourse', 'mafia')]
    sfx += [{'file': 'vo/v5/braam.mp3', 'at': s['finale'][0], 'gain': 1.0}]
    (here / 'v5-trailer.timeline.js').write_text(
        '// Generated by v5_timeline.py from the ElevenLabs narrator lengths. Do not edit by hand.\n'
        'window.TL = ' + json.dumps({'scenes': scenes, 'end': end}, indent=1) + ';\n', encoding='utf-8')
    html = here / 'v5-trailer.html'
    if html.exists():
        h = html.read_text(encoding='utf-8')
        html.write_text(re.sub(r'data-duration="[\d.]+"', f'data-duration="{end}"', h), encoding='utf-8')
    plan = {
        'video': 'out/v5-trailer.video.mp4', 'html': 'v5-trailer.html',
        # the tense middle of the dark piece under the hook, then the epic piece from the logo on
        'music': 'vo/v5/musicA.mp3', 'music_offset': 6.0, 'music_until': s['logo'][0] + 0.3,
        'music2': 'vo/v5/musicB.mp3', 'music2_offset': 0, 'music2_at': s['logo'][0],
        'music_soft': [s['girls'][0], s['girls'][1]],   # the epic music steps back for Nadia
        'lines': lines, 'sfx': sfx, 'no_synth_sfx': True,
        'out': 'out/v5-trailer-vo.mp4',
    }
    (vo / 'plan.json').write_text(json.dumps(plan, indent=1))
    (vo / 'tmp.wav').unlink()
    for n, (a, b) in scenes.items():
        print(f'{n:8s} {a:6.2f} → {b:6.2f}')
    print('end', end)


if __name__ == '__main__':
    main()
